default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: video_streaming_api_development

test:
  <<: *default
  database: video_streaming_api_test

production:
  <<: *default
  database: video_streaming_api_production
  username: video_streaming_api
  password: <%= ENV['VIDEO_STREAMING_API_DATABASE_PASSWORD'] %>
